### ISSUE TITLE
建议 Suggestions

### ISSUE THREAD

**Issue by weiensong** [weiensong/scrapySelenium#4]
it is about suggestions
建议请在这里提交

**Comment by Quasimurdock** [comment]
Hi @weiensong really appreciate ur efforts!

Srry to bother u. But I wanna know if it's possible that u could add some **use-cases** in README?
 
That would be more helpful!

**Comment by weiensong** [comment]
Hi bro, I agree with you and will fix it in&nbsp;recently, please follow it.


Thank you!!




Tlouer_Elle
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiensong/carp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月6日(星期三) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiensong/carp] 建议 Suggestions (Issue #4)





 
Hi @weiensong really appreciate ur efforts!
 
Srry to bother u. But I wanna know if it's possible that u could add some use-cases in README?
 
That would be more helpful!
